production:
  cleanup_availability_slots:
    class: CleanupAvailabilitySlotsJob
    queue: default
    schedule: at 12am every day

development:
  cleanup_availability_slots:
    class: CleanupAvailabilitySlotsJob
    queue: default
    schedule: at 12am every day
