chartVersion: 0.2.5

project:
  name: "booking"

repository:
  name: "markmorcos/booking"
  path: "."

ingress:
  host: booking.morcos.tech
  rules:
    - host: booking.morcos.tech
      path: /(.*)
      pathType: ImplementationSpecific
      serviceName: booking-service

deployments:
  - name: booking
    image: markmorcos/booking

services:
  - name: booking-service
    port: 80
