FROM ruby:3.2.2-slim

# Install dependencies
RUN apt-get update -qq && apt-get install -y \
    build-essential \
    libpq-dev \
    curl \
    git \
    nodejs \
    npm \
    postgresql-client \
    vim \
    && npm install -g yarn \
    && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Set working directory
WORKDIR /app

# Install bundler
RUN gem install bundler

# Copy Gemfile and install gems
COPY Gemfile Gemfile.lock ./
RUN bundle install

# Copy package.json and install packages
COPY package.json yarn.lock ./
RUN yarn install

# Copy the rest of the application
COPY . .

# Add a default command for development
CMD ["bash", "-c", "rm -f tmp/pids/server.pid && bundle exec rails server -p 3000 -b '0.0.0.0'"] 