version: "3.8"

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fr_youhanna_makin_development
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/fr_youhanna_makin_development
      RAILS_ENV: development
      ADMIN_EMAIL: admin@example.com
      ADMIN_PASSWORD: password
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      WEBPACKER_DEV_SERVER_HOST: webpacker
    tty: true
    stdin_open: true

  webpacker:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ./bin/webpack-dev-server
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
      - node_modules:/app/node_modules
    ports:
      - "3035:3035"
    environment:
      NODE_ENV: development
      RAILS_ENV: development
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0

volumes:
  postgres_data:
  bundle_cache:
  node_modules:
