// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $admin_middleware from "./routes/admin/_middleware.ts";
import * as $admin_availability from "./routes/admin/availability.tsx";
import * as $admin_index from "./routes/admin/index.tsx";
import * as $admin_login from "./routes/admin/login.tsx";
import * as $api_admin_appointments_id_ from "./routes/api/admin/appointments/[id].tsx";
import * as $api_admin_login from "./routes/api/admin/login.tsx";
import * as $api_admin_logout from "./routes/api/admin/logout.tsx";
import * as $api_admin_slots from "./routes/api/admin/slots.tsx";
import * as $api_admin_slots_batch from "./routes/api/admin/slots/batch.tsx";
import * as $api_book from "./routes/api/book.tsx";
import * as $index from "./routes/index.tsx";
import * as $AdminHeader from "./islands/AdminHeader.tsx";
import * as $AppointmentBooking from "./islands/AppointmentBooking.tsx";
import * as $AppointmentList from "./islands/AppointmentList.tsx";
import * as $BookingForm from "./islands/BookingForm.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $CreateSlotForm from "./islands/CreateSlotForm.tsx";
import * as $LoginIsland from "./islands/LoginIsland.tsx";
import * as $SlotList from "./islands/SlotList.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/admin/_middleware.ts": $admin_middleware,
    "./routes/admin/availability.tsx": $admin_availability,
    "./routes/admin/index.tsx": $admin_index,
    "./routes/admin/login.tsx": $admin_login,
    "./routes/api/admin/appointments/[id].tsx": $api_admin_appointments_id_,
    "./routes/api/admin/login.tsx": $api_admin_login,
    "./routes/api/admin/logout.tsx": $api_admin_logout,
    "./routes/api/admin/slots.tsx": $api_admin_slots,
    "./routes/api/admin/slots/batch.tsx": $api_admin_slots_batch,
    "./routes/api/book.tsx": $api_book,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/AdminHeader.tsx": $AdminHeader,
    "./islands/AppointmentBooking.tsx": $AppointmentBooking,
    "./islands/AppointmentList.tsx": $AppointmentList,
    "./islands/BookingForm.tsx": $BookingForm,
    "./islands/Counter.tsx": $Counter,
    "./islands/CreateSlotForm.tsx": $CreateSlotForm,
    "./islands/LoginIsland.tsx": $LoginIsland,
    "./islands/SlotList.tsx": $SlotList,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
