chartVersion: 0.2.5

project:
  name: "booking"

repository:
  name: "markmorcos/booking"
  path: "backend"

ingress:
  host: booking.morcos.tech
  rules:
    - host: booking.morcos.tech
      path: /(.*)
      pathType: ImplementationSpecific
      serviceName: booking-service

deployments:
  - name: booking-deployment
    image: markmorcos/booking
    env:
      - name: RAILS_ENV
        value: production
      - name: PGHOST
        valueFrom:
          secretKeyRef:
            name: postgres-secrets
            key: PGHOST
      - name: PGUSER
        valueFrom:
          secretKeyRef:
            name: postgres-secrets
            key: PGUSER
      - name: PGPASSWORD
        valueFrom:
          secretKeyRef:
            name: postgres-secrets
            key: PGPASSWORD
      - name: PGDATABASE
        valueFrom:
          secretKeyRef:
            name: postgres-secrets
            key: PGDATABASE
      - name: PGPORT
        valueFrom:
          secretKeyRef:
            name: postgres-secrets
            key: PGPORT
      - name: SECRET_KEY_BASE
        valueFrom:
          secretKeyRef:
            name: rails-secret
            key: SECRET_KEY_BASE

services:
  - name: booking-service
    port: 80
