chartVersion: 0.2.8

project:
  name: "booking"

repository:
  name: "markmorcos/booking"
  path: "backend"

ingress:
  host: booking.morcos.tech
  rules:
    - host: booking.morcos.tech
      path: /(.*)
      pathType: ImplementationSpecific
      serviceName: booking-service

deployments:
  - name: booking-deployment
    image: markmorcos/booking
    env:
      - name: RAILS_ENV
        value: production
      - name: DATABASE_URL
        valueFrom:
          secretKeyRef:
            name: database-secret
            key: DATABASE_URL
      - name: SECRET_KEY_BASE
        valueFrom:
          secretKeyRef:
            name: rails-secret
            key: SECRET_KEY_BASE
      - name: SMTP_ADDRESS
        valueFrom:
          secretKeyRef:
            name: smtp-secrets
            key: SMTP_ADDRESS
      - name: SMTP_DOMAIN
        valueFrom:
          secretKeyRef:
            name: smtp-secrets
            key: SMTP_DOMAIN
      - name: SMTP_PORT
        valueFrom:
          secretKeyRef:
            name: smtp-secrets
            key: SMTP_PORT
      - name: SMTP_USERNAME
        valueFrom:
          secretKeyRef:
            name: smtp-secrets
            key: SMTP_USERNAME
      - name: SMTP_PASSWORD
        valueFrom:
          secretKeyRef:
            name: smtp-secrets
            key: SMTP_PASSWORD

services:
  - name: booking-service
    port: 80

jobs:
  - name: prepare-database-job
    image: markmorcos/booking
    command: ["bundle", "exec", "rails", "db:create", "db:migrate", "db:seed"]
