FROM golang:1.22-alpine AS builder
WORKDIR /build
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o server ./cmd/server

FROM alpine:3.19
RUN apk add --no-cache ca-certificates tzdata
COPY --from=builder /build/server /app/server
COPY --from=builder /build/db/migrations /app/migrations
COPY --from=builder /build/internal/notification/templates /app/templates
EXPOSE 8080
CMD ["/app/server"]
