apiVersion: batch/v1
kind: Job
metadata:
  name: rails-db-migrate
  namespace: booking
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migrate
          image: markmorcos/booking:latest
          command:
            [
              "sh",
              "-c",
              "bundle exec rails db:create && bundle exec rails db:migrate",
            ]
          env:
            - name: RAILS_ENV
              value: production
            - name: PGHOST
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: PGHOST
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: PGUSER
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: PGPASSWORD
            - name: PGDATABASE
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: PGDATABASE
            - name: PGPORT
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: PGPORT
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: rails-secret
                  key: SECRET_KEY_BASE
