apiVersion: batch/v1
kind: Job
metadata:
  name: create-admin-user
  namespace: booking
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migrate
          image: markmorcos/booking:latest
          command: ["rails", "db:create", "db:migrate", "db:seed"]
          env:
            - name: RAILS_ENV
              value: production
            - name: PGHOST
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: PGHOST
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: PGUSER
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: PGPASSWORD
            - name: PGDATABASE
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: PGDATABASE
            - name: PGPORT
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: PGPORT
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: rails-secret
                  key: SECRET_KEY_BASE
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: admin-secret
                  key: ADMIN_PASSWORD
