apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fr-youhanna-makin-storage
  labels:
    app: fr-youhanna-makin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: do-block-storage
