default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary: &primary_development
    <<: *default
    database: fr_youhanna_makin_development
    username: postgres
    password: postgres
    host: localhost
    port: 5432
  queue:
    <<: *primary_development
    database: fr_youhanna_makin_development_queue
    migrations_paths: db/queue_migrate

test:
  <<: *default
  database: fr_youhanna_makin_test
  username: postgres
  password: postgres
  host: localhost
  port: 5432

production:
  primary: &primary_production
    <<: *default
    database: <%= ENV["PGDATABASE"] %>
    username: <%= ENV["PGUSER"] %>
    password: <%= ENV["PGPASSWORD"] %>
    host: <%= ENV["PGHOST"] %>
    port: <%= ENV["PGPORT"] %>
  queue:
    <<: *primary_production
    migrations_paths: db/queue_migrate
