name: deploy-infrastructure-admin

on:
  workflow_dispatch: {}
  push:
    branches: [main]
    paths: ["admin/**"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger booking deployment
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.INFRASTRUCTURE_TOKEN }}
          repository: markmorcos/booking
          event-type: deploy-booking
          client-payload: |-
            {
              "repository": "markmorcos/booking",
              "token": "${{ secrets.DEPLOYMENT_TOKEN }}",
              "version": "${{ github.sha }}",
              "config_file": "deployment.yaml"
            }
