name: Migrate Database

on:
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Rails DB migration job
        run: |
          echo "${{ secrets.RASPBERRY_PI_SSH_KEY }}" > /tmp/id_rsa
          chmod 600 /tmp/id_rsa

          ssh -o StrictHostKeyChecking=no -i /tmp/id_rsa ${{ secrets.RASPBERRY_PI_USERNAME }}@${{ secrets.RASPBERRY_PI_HOST }} \
            "KUBECONFIG=\$HOME/.kube/config && \
            kubectl delete job/rails-db-migrate -n fr-youhanna-makin && \
            kubectl apply -f - && \
            kubectl wait --for=condition=complete job/rails-db-migrate -n fr-youhanna-makin --timeout=120s && \
            kubectl logs job/rails-db-migrate -n fr-youhanna-makin" < k8s/04-migration.yaml
